name = "sales-execution-hub"
main = "src/worker.js"
compatibility_date = "2026-08-04"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "sales-execution-hub"
database_id = "1b8c75cb-6021-4a15-802a-f81b831c089f"
migrations_dir = "migrations"
